### ISSUE TITLE
Any clear timeline or a plan for open-source code?

### ISSUE THREAD

**Issue by skykiseki** [mayubo2333/LLM-IE#1]
Thx

**Comment by mayubo2333** [comment]
Thanks for your interest on our work. I'm sorry that I'm struggle to meet a ddl on 15th January, so I plan to make the code publicly available after that. Sorry for the delay.

**Comment by skykiseki** [comment]
> Thanks for your interest on our work. I'm sorry that I'm struggle to meet a ddl on 15th January, so I plan to make the code publicly available after that. Sorry for the delay.

OK! Looking forward to the latest updates.
