### ISSUE TITLE
Looking forward to the code!

### ISSUE THREAD

**Issue by Moxuan0517** [mayubo2333/LLM-IE#3]
Hello!
I have recently read your paper: "Large Language Model Is Not a Good Few-shot Information Extractor, but a Good Reranker for Hard Samples!". The  work is interesting and attractive to me. I am wondering if you could kindly share the source code.
Thanks!

**Comment by mayubo2333** [comment]
So sorry for the delay! Next weekkkk!

**Comment by mayubo2333** [comment]
> Hello! I have recently read your paper: "Large Language Model Is Not a Good Few-shot Information Extractor, but a Good Reranker for Hard Samples!". The work is interesting and attractive to me. I am wondering if you could kindly share the source code. Thanks!

Released. Thanks for your interest.
