### ISSUE TITLE
Figure 5

### ISSUE THREAD

**Issue by jw9603** [mayubo2333/LLM-IE#5]
Hi,

Where is the code for the "Figure 5" part?

**Comment by mayubo2333** [comment]
> Hi,
> 
> Where is the code for the "Figure 5" part?

Hi,

For now, this repo is only about the LLM reranker. I can consider adding the SLM-related code in the future.

**Comment by jw9603** [comment]
Could you explain this figure in detail?

Did you perform fine-tuning on the data when calculating the confidence score?

**Comment by mayubo2333** [comment]
Yes, the confidence scores are calculated by small LMs which are fine-tuned on in-domain samples.

**Comment by mayubo2333** [comment]
> Could you explain this figure in detail?
> 
> Did you perform fine-tuning on the data when calculating the confidence score?

Yes, the confidence scores are calculated by small LMs which are fine-tuned on in-domain samples.
