### ISSUE TITLE
Some requests.

### ISSUE THREAD

**Issue by simon-p-j-r** [mayubo2333/LLM-IE#6]
Dear Doc.Ma

Thank u for your amanzing work and for publishing parts of the code.

I request that you disclose the relevant code for using Open-source models, rather than just OpenAI models.

Your previous work on PAIE is a highly inspiring piece. I request that you disclose the ensemble code related to SLM for PAIE and LLM on RAMS dataset.

Thank u very much.

**Comment by mayubo2333** [comment]
> Dear Doc.Ma
> 
> Thank u for your amanzing work and for publishing parts of the code.
> 
> I request that you disclose the relevant code for using Open-source models, rather than just OpenAI models.
> 
> Your previous work on PAIE is a highly inspiring piece. I request that you disclose the ensemble code related to SLM for PAIE and LLM on RAMS dataset.
> 
> Thank u very much.

Thanks for your interest for this work (and PAIE). 

1. It's a good idea. I will clead the code about open-source models and release it soon.
2. PAIE is a EAE model. However, we only evaluate our filter-then-reranker system on NER, RE and ED tasks. Maybe you can try to incorporate these two models by yourself? I think our method is likely to be effective on EAE task too.

**Comment by simon-p-j-r** [comment]
Thank u very much. I look forward to your code.

I'm eagerly anticipating your future work. PAIE, LLM-IE, and Few-shot ED are all highly inspiring. Thank you!

**Comment by mayubo2333** [comment]
> Thank u very much. I look forward to your code.
> 
> I'm eagerly anticipating your future work. PAIE, LLM-IE, and Few-shot ED are all highly inspiring. Thank you!

I have added modules adapting open-source LLMs as the rerankers. Please check the code.
Thanks for your encouraging feedback for my work! Best wishes for your research as well

**Comment by simon-p-j-r** [comment]
It's work! Thank u again!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mayubo2333/LLM-IE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月12日(星期五) 下午2:46
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [mayubo2333/LLM-IE] Some requests. (Issue #6)





  
Thank u very much. I look forward to your code.
 
I'm eagerly anticipating your future work. PAIE, LLM-IE, and Few-shot ED are all highly inspiring. Thank you!
  
I have added modules adapting open-source LLMs as the rerankers. Please check the code.
 Thanks for your encouraging feedback for my work! Best wishes for your research as well
