### ISSUE TITLE
Confusion regarding the demonstrations used for the re-ranking strategy.

### ISSUE THREAD

**Issue by anushkasw** [mayubo2333/LLM-IE#8]
Hello,

You have provided four demonstrations for the relation extraction task from the Tacrev dataset. The paper also mentions that four demonstrations were used for the reranking task. How did you choose these demonstrations? Also, were the demonstrations kept constant irrespective of the hard sample that was getting reranked?

**Comment by mayubo2333** [comment]
Hello,

The demonstrations are manually written by us. We feed all of them to LLMs. And they are irrespective of hard samples, i.e., all hard samples use the same demonstrations.

**Comment by anushkasw** [comment]
Oh ok. So, will the prompts remain the same for both tacred and tacrev datasets?
Also, if I were to use your method on any other dataset, are there any rules to be followed while coming up with the demonstrations?

**Comment by mayubo2333** [comment]
Yes, I think the prompts also work for tacred dataset since they share the same label set.

For other datasets, I would suggest you to select some hard samples (according to the performance of Small LMs) and manually write some demonstrations. And do follow the label set of your new dataset.

**Comment by anushkasw** [comment]
Got it. Thanks for the information

**Comment by mayubo2333** [comment]
You are welcome, and I will close this issue. Feel free to re-open it if you have other questions in the future.
